var productionlist = {
title:["作品名正式名称","英文名称","日本語コピーライト","copyright","Short copyright","製作年","カテゴリー","尺/話数"],
list :[
        ["ウルトラマンジード","Ultraman Geed","円谷プロ　ウルトラマンジード製作委員会・テレビ東京","©TSUBURAYA PROD.©ULTRAMANGEED PRODUCTION CONSORTIUM・TV TOKYO","","2017","TV series","[30min/25EP]"],
        ["劇場版ウルトラマンオーブ　絆の力、おかりします！","ULTRAMAN ORB THE MOVIE","© 劇場版ウルトラマンオーブ製作委員会","©2017 UO FILM PARTNERS","","2017","Film","70min"],
        ["ウルトラマンオーブ THE ORIGIN SAGA","Ultraman Orb The Origin Saga","©2017円谷プロ","©2017 TSUBURAYA PRODUCTIONS","","2017","TV series","[30min/12EP]"],
        ["ウルトラマンゼロ THE CHRONICLE","Ultraman Zero:The Chronicle","©2017円谷プロ","©2017 TSUBURAYA PRODUCTIONS","","2017","TV series","[30min/25EP]"],
        ["怪獣娘","Kaiju Girls","©円谷プロ","©TSUBURAYA PRODUCTIONS ©KAIJU GIRLS PRODUCTION CONSORTIUM","©TPC ©KGPC","2016","Anime","[５min/12EP]"],
        ["ウルトラマンオーブ","ULTRAMAN ORB","©円谷プロ　(C)ウルトラマンオーブ製作委員会・テレビ東京","©TSUBURAYA PROD.©ULTRAMANORB PRODUCTION CONSORTIUM・TV TOKYO","©TPC ©UO・TX","2016","TV SERIES","[30min/25EP]"],
        ["劇場版ウルトラマンX","ULTRAMAN X The Movie","©2016「劇場版ウルトラマンX」製作委員会","©2016 UX FILM PARTNERS","","2016","FILM","63min"],
        ["ウルトラファイトビクトリー","Ultra Fight Victory","©2015 円谷プロ","©2015 TSUBURAYA PRODUCTIONS","","2015","","3ｍin"],
        ["劇場版 ウルトラマンギンガS 決戦！ウルトラ１０勇士！！","Ultraman Ginga S the movie","©2015「劇場版 ウルトラマンギンガＳ」製作委員会","©2015 ULTRAMAN GINGA S FILM PARTNERS","","2015","Film","63min"],
        ["ウルトラマンX","Ultraman　X","©2015 ウルトラマンエックス製作委員会","©2015 TSUBURAYA PRODUCTIONS","","2015","TV series","[30min/24EP]"],
        ["ウルトラマンギンガS","Ultraman Ginga S","©2014 円谷プロ","©2014 TSUBURAYA PRODUCTIONS","","2014","TV series","[30min/16EP]"],
        ["ネオ・ウルトラQ","Neo Ultra Q","©2013円谷プロ・WOWOW","©2013 TSUBURAYA PRODUCTIONS・WOWOW","","2013","Film","[30min/12EP]"],
        ["ウルトラマンギンガ","Ultraman Ginga","©2013円谷プロ","©2013 TSUBURAYA PRODUCTIONS","","2013","TV series","[30min/11EP]"],
        ["ウルトラマンギンガ劇場スペシャル","Ultraman Ginga Theater Special","©2013円谷プロ","©2013 TSUBURAYA PRODUCTIONS","","2013","Film",""],
        ["ウルトラマンギンガ劇場スペシャル ウルトラ怪獣☆ヒーロー大乱戦!","Ultraman Ginga Theater Special Ultra Monster ☆ Hero Battle Royal!","©2013円谷プロ","©2013 TSUBURAYA PRODUCTIONS","","2013","Film",""],
        ["ウルトラマンゼロクロニクル","Ultraman Zero The Chronicle","©2013円谷プロ","©2013 TSUBURAYA PRODUCTIONS","","2013","TV series","[30min/25EP]"],
        ["ウルトラマン列伝 ウルトラゼロファイト","ULTRA ZERO FIGHT","©2012円谷プロ","©2012 TSUBURAYA PRODUCTIONS","","2012","Film",""],
        ["ウルトラマンSAGA","Ultraman Saga","©2011「ウルトラマンサーガ」製作委員会","©2011 Ultraman Saga Film Partners","","2011","Film","90min"],
        ["ウルトラマンゼロ外伝 キラー ザ ビートスター (Stage1 & 2)","Ultraman Zero Side Story: Killer the Beatstar (STAGE1： Steel Invasion & STAGE2：Vows of Justice)","©円谷プロ","©2011 TSUBURAYA PRODUCTIONS","","2011","Original Video","31min&32min"],
        ["ウルトラ銀河伝説外伝 ウルトラマンゼロVSダークロプスゼロ (Stage1 & 2)","ULTRA GALAXY LEGEND SIDE STORY: ULTRAMAN ZERO VS DARKLOPS ZERO (Stage1：Colliding Space & Stage2：Zero's Final","©円谷プロ","©2010 TSUBURAYA PRODUCTIONS","","2010","Original Video","32min&32min"],
        ["ウルトラマンゼロ THE MOVIE 超決戦! ベリアル銀河帝国","ULTRAMAN ZERO: THE REVENGE OF BELIAL","©2010 「ウルトラマンゼロ THE MOVIE」製作委員会","©2010 UZ-ROB Film Partners","","2010","Film","100min"],
        ["大怪獣バトル ウルトラ銀河伝説","MEGA MONSTER BATTLE ULTRA GALAXY: THE MOVIE","©2009 「大怪獣バトル ウルトラ銀河伝説」製作委員会","©2009 MMB-UG Film Partners","","2009","Film","96min"],
        ["ウルトラマンメビウス外伝 ゴーストリバース (Stage1 & 2)","ULTRAMAN MEBIUS Side Story: GHOST REBIRTH　STAGE1: Graveyard of Darkness STAGE2: Emperor of Resurrection","©2009 円谷プロ","©2009 TSUBURAYA PRODUCTIONS","","2009","Original Video","26min&26min"],
        ["大決戦!超ウルトラ8兄弟","SUPERIOR 8 ULTRAMAN BROTHERS","©2008『大決戦！超ウルトラ8兄弟』製作委員会","©2008 SUPERIOR 8 ULTRAMAN BROTHERS Production Consortium","","2008","Film","97min"],
        ["ウルトラギャラクシー大怪獣バトル NEVER ENDING ODYSSEY","ULTRA GALAXY MEGA MONSTER BATTLE: SEASON2 NEVER ENDING ODYSSEY","©2008円谷プロ・UGプロジェクト","©2008 TSUBURAYA PRODUCTIONS ・ UG Project","","2008","TV series","[30min/13EP]"],
        ["ウルトラマンマックス クライマックスストーリーズ","ULTRAMAN MAX: CLIMAX STORY","","#N/A","","2008","Original Video","60min"],
        ["ウルトラマンメビウス外伝 アーマードダークネス　(Stage1 & 2)","ULTRAMAN MEBIUS SIDE STORY: ARMORED DARKNESS (STAGE 1 &","©2008 円谷プロ","©2008 TSUBURAYA PRODUCTIONS","","2008","Original Video","24min&24min"],
        ["ウルトラギャラクシー大怪獣バトル","ULTRA GALAXY MEGA MONSTER BATTLE: SEASON1","©2007円谷プロ","©2007 TSUBURAYA PRODUCTIONS","","2007","TV series","[30min/13EP]"],
        ["ウルトラセブン X","ULTRA SEVEN X","©2007円谷プロ","©2007 ULTRASEVEN X PROJECT","","2007","TV series","[30min/6EP]"],
        ["ミラーマン REFLEX","MIRROR MAN: REFLEX","©2006円谷プロ","©2006 TSUBURAYA PRODUCTIONS","","2006","Non Ult.","[50min/3EP]"],
        ["ウルトラマンメビウス","ULTRAMAN MEBIUS","©2006円谷プロ","©2006 TSUBURAYA PRODUCTIONS","","2006","TV series","[30min/50EP]"],
        ["ウルトラマンメビウス&ウルトラ兄弟","ULTRAMAN MEBIUS & ULTRAMAN BROTHERS","©2006 ｳﾙﾄﾗﾏﾝﾒﾋﾞｳｽ＆ｳﾙﾄﾗ兄弟製作委員会","©2006 ULTRAMAN MEBIUS &ULTRAMAN BROTHERS Production","","2006","Film","93min"],
        ["ウルトラマンメビウス外伝 ヒカリサーガ","ULTRAMAN MEBIUS SIDE STORY: HIKARI SAGA","","©2006 TSUBURAYA PRODUCTIONS","","2006","Original Video","40min"],
        ["ウルトラマンマックス","ULTRAMAN MAX","©2005円谷プロ","©2005 TSUBURAYA PRODUCTIONS","","2005","TV series","[30min/40EP]"],
        ["ウルトラマンマックス　怪獣大図鑑","ULTRAMAN MAX: MONSTER ENCYCLOPEDIA 1","","#N/A","","2005","Original Video","30min"],
        ["ウルトラマンマックス　怪獣大図鑑2","ULTRAMAN MAX: MONSTER ENCYCLOPEDIA 2","","#N/A","","2005","Original Video","32min&32min"],
        ["ウルトラマンネクサス","ULTRAMAN NEXUS","©2004円谷プロ","©2004 TSUBURAYA PRODUCTIONS","","2004","TV series","[30min/37EP]"],
        ["ULTRAMAN","ULTRAMAN: THE NEXT","©2004 映画ｳﾙﾄﾗﾏﾝｻﾞﾈｸｽﾄ","©2004 ULTRAMAN: THE NEXT Production Consortium","","2004","Film","97min"],
        ["オタスケガール",,"","#N/A","","2003","Non Ult.","[30min/65EP]"],
        ["ウルトラマンコスモスVSウルトラマンジャスティス THE FINAL BATTLE","ULTRAMAN COSMOS VS ULTRAMAN JUSTICE: THE FINAL BATTLE","©2003映画ｳﾙﾄﾗﾏﾝｺｽﾓｽVSｼﾞｬｽﾃｨｽ","©2003 TSUBURAYA PRODUCTIONS ©2003 Ultraman Cosmos vs Ultraman Justice Movie Production Consortium","","2003","Film","77min"],
        ["新世紀ウルトラマン伝説","NEW CENTURY ULTRAMAN LEGEND","©2002 円谷プロ　　©2002 ウルトラマン伝説プロジェクト","©2002 New Century Ultraman Legend Project","","2002","Film","15min"],
        ["新世紀2003ウルトラマン伝説 THE KING'S JUBILEE","NEW CENTURY ULTRAMAN LEGEND 2003","©2003 円谷プロ　　　　©2003 ウルトラマン伝説プロジェクト","©2003 New Century Ultraman Legend 2 Project","","2002","Film","20min"],
        ["ウルトラセブン誕生35周年\"EVOLITION\"5部作","ULTRA SEVEN","©2002円谷プロ","©2002 TSUBURAYA PRODUCTIONS","","2002","Original Video","[45min/5EP]"],
        ["ウルトラマンコスモス2 THE BLUE PLANET","ULTRAMAN COSMOS: THE BLUE PLANET","©2002映画ｳﾙﾄﾗﾏﾝｺｽﾓｽ-2製作委員会","©2002 TSUBURAYA PRODUCTIONS ©2002 Ultraman Cosmos 2 Movie Production Consortium","","2002","Film","75min"],
        ["ウルトラマンコスモス","ULTRAMAN COSMOS","©2001円谷プロ","©2001 TSUBURAYA PRODUCTIONS","","2001","TV series","[30min/65EP]"],
        ["ウルトラマンコスモス THE FIRST CONTACT","ULTRAMAN COSMOS: THE FIRST CONTACT","©2001映画ｳﾙﾄﾗﾏﾝｺｽﾓｽ製作委員会","©2001 TSUBURAYA PRODUCTIONS ©2001 Ultraman Cosmos Movie Production Consortium","","2001","Film","[90min]"],
        ["ウルトラマンダイナ 帰ってきたハネジロー","ULTRAMAN DYNA: RETURN OF HANEJIRO","©2001円谷プロ","©2001 TSUBURAYA PRODUCTIONS","","2001","Original Video","[45min]"],
        ["ウルトラマンガイア ガイアよ再び","ULTRAMAN GAIA: ONCE AGAIN GAIA","","©2001 TSUBURAYA PRODUCTIONS","","2001","Original Video","[45min]"],
        ["ウルトラマンティガ外伝 古代に蘇る巨人","ULTRAMAN TIGA: REVIVAL OF THE ANCIENT GIANT","©2001円谷プロ","©2001 TSUBURAYA PRODUCTIONS","","2001","Original Video","[45min]"],
        ["ウルトラマンネオス","ULTRAMAN NEOS","©2000円谷プロ","©2000 TSUBURAYA PRODUCTIONS","","2000","Original Video","[30min/12EP]"],
        ["ウルトラマンティガ THE FINAL ODYSSEY","ULTRAMAN TIGA: THE FINAL ODYSSEY","©2000 映画ｳﾙﾄﾗﾏﾝﾃｲｶﾞ製作委員会","©2000 Tsuburaya Prodcutions ©2000 Ultraman Tiga Movie Production Consortium","","2000","Film","85min"],
        ["ウルトラマンM78劇場 Love&Peace",,"©1999円谷プロ ©1999ウルトラマンＭ７８製作委員会","©1999 TSUBURAYA PRODUCTIONS ©1999 M-78 Theater Production Consortium","","1999","Anime","30min"],
        ["ブースカ! ブースカ!!","BOOSKA","©1999円谷プロ","©1999 TSUBURAYA PRODUCTIONS","","1999","Non Ult.","[30min/38EP]"],
        ["ウルトラセブン1999最終章6部作","ULTRA SEVEN","©1999円谷プロ","©1999 TSUBURAYA PRODUCTIONS","","1999","Original Video","[60min/6EP]"],
        ["ウルトラマンナイス","ULTRAMAN NICE","©円谷プロ","©1999 TSUBURAYA PRODUCTIONS","","1999","TV series","20min"]
        ]
};


